from selenium import webdriver
import time
#http://automationpractice.com is the site for selenium automation
browser=webdriver.Chrome("C:/Users/DELL/Desktop/chromedriver.exe")
browser.get("http://automationpractice.com")
browser.maximize_window()
browser.find_element_by_class_name("login").click()
browser.find_element_by_id("email_create").send_keys("sinacengiz@yandex.com")
browser.find_element_by_name("SubmitCreate").click()
time.sleep(10)
browser.find_element_by_id("id_gender2").click()
browser.find_element_by_id("customer_firstname").send_keys("sina")
browser.find_element_by_id("customer_lastname").send_keys("cengiz")
browser.find_element_by_id("passwd").send_keys("devil")
browser.find_element_by_id("days").send_keys("5")
browser.find_element_by_id("months").send_keys("January")
browser.find_element_by_id("years").send_keys("1980")
browser.find_element_by_id("newsletter").click()
browser.find_element_by_id("optin").click()
browser.find_element_by_id("company").send_keys("esgen yapi denetim")
browser.find_element_by_id("address1").send_keys("nuri duyguer sk. baris apt")
browser.find_element_by_id("address2").send_keys("numara 2 daire 1")
browser.find_element_by_id("city").send_keys("eskisehir")
browser.find_element_by_id("id_state").send_keys("Alabama")
browser.find_element_by_id("id_state").send_keys("Alabama")
browser.find_element_by_id("postcode").send_keys("00000")
browser.find_element_by_id("id_country").send_keys("United States")
browser.find_element_by_id("other").send_keys("awesome")
browser.find_element_by_id("phone").send_keys("2163451634")
browser.find_element_by_id("other").send_keys("awesome")
browser.find_element_by_id("phone_mobile").send_keys("3467888")
browser.find_element_by_id("alias").send_keys("dwww")
browser.find_element_by_id("submitAccount").click()
time.sleep(9)
browser.close()